import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="antialiased">

        <div className="navbar bg-base-100 shadow-md">
          <div className="flex-1">

            <Link href="/" className="btn btn-ghost text-xl">
              Sociolli
            </Link>

            <input
              type="text"
              placeholder="Search"
              className="input input-bordered rounded-none w-64 md:w-96 lg:w-auto"
            />
          </div>


          <div className="form-control flex gap-4 justify-between">

            <div className="flex-grow">
              <Link href="/" className="btn btn-ghost text-xl">
                Login
              </Link>
            </div>
          </div>

          <div>
              <div className="indicator">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-6 w-6"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z"
                  />
                </svg>
                <span className="badge badge-sm indicator-item">8</span>
              </div>
            </div>


          <div className="flex-none gap-2">
            <div className="dropdown dropdown-end">
              <div
                tabIndex={0}
                role="button"
                className="btn btn-ghost btn-circle avatar"
              >
              </div>
              <ul
                tabIndex={0}
                className="menu menu-sm dropdown-content mt-3 z-[1] w-52 bg-base-100 rounded-box shadow"
              >
                <li>
                  <Link href="/profile">
                    Profile
                    <span className="badge">New</span>
                  </Link>
                </li>
                <li>
                  <Link href="/settings">Settings</Link>
                </li>
                <li>
                  <a>Logout</a>
                </li>
              </ul>
            </div>
          </div>
        </div>


        <div className="bg-base-100 py-2 shadow-inner">
          <div className="container mx-auto">
            <ul className="menu menu-horizontal px-4">
              <li>
                <Link href="/category1">Categories</Link>
              </li>
              <li>
                <Link href="/category2">Brand</Link>
              </li>

            </ul>
          </div>
        </div>


        <main className="container mx-auto p-4">{children}</main>
      </body>
    </html>
  );
}
